//go:build ignore

package main

import (
	"encoding/csv"
	"fmt"
	"log"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	registryURL = "https://www.iana.org/assignments/as-numbers/as-numbers-2.csv"
	outputFile  = "asn_ranges_gen.go"
	// Only rows delegated to an RIR are permitted; everything else in the
	// registry is Unallocated, Reserved, or Reserved for Private Use.
	assignedPrefix = "Assigned by "
)

type asnRange struct{ start, end uint32 }

func main() {
	rows, err := fetchRegistry()
	if err != nil {
		log.Fatalf("fetch registry: %v", err)
	}

	ranges, err := parseAssignedRanges(rows)
	if err != nil {
		log.Fatalf("parse registry: %v", err)
	}
	if len(ranges) == 0 {
		log.Fatal("no assigned ranges found; refusing to write an empty table")
	}

	if err := writeTable(ranges); err != nil {
		log.Fatalf("write %s: %v", outputFile, err)
	}
	log.Printf("wrote %s with %d assigned ranges", outputFile, len(ranges))
}

func fetchRegistry() ([][]string, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(registryURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %s", resp.Status)
	}
	return csv.NewReader(resp.Body).ReadAll()
}

func parseAssignedRanges(rows [][]string) ([]asnRange, error) {
	var ranges []asnRange
	for i, row := range rows {
		if i == 0 || len(row) < 2 {
			continue
		}
		if !strings.HasPrefix(row[1], assignedPrefix) {
			continue
		}
		r, err := parseRange(row[0])
		if err != nil {
			return nil, fmt.Errorf("row %d: %w", i+1, err)
		}
		ranges = append(ranges, r)
	}
	sort.Slice(ranges, func(i, j int) bool { return ranges[i].start < ranges[j].start })
	return ranges, nil
}

// parseRange handles both "131072-132095" and bare "4294967295" forms.
func parseRange(field string) (asnRange, error) {
	field = strings.TrimSpace(field)
	startStr, endStr, isRange := strings.Cut(field, "-")
	if !isRange {
		endStr = startStr
	}
	start, err := strconv.ParseUint(strings.TrimSpace(startStr), 10, 32)
	if err != nil {
		return asnRange{}, fmt.Errorf("bad start in %q: %w", field, err)
	}
	end, err := strconv.ParseUint(strings.TrimSpace(endStr), 10, 32)
	if err != nil {
		return asnRange{}, fmt.Errorf("bad end in %q: %w", field, err)
	}
	if end < start {
		return asnRange{}, fmt.Errorf("end before start in %q", field)
	}
	return asnRange{start: uint32(start), end: uint32(end)}, nil
}

func writeTable(ranges []asnRange) error {
	var b strings.Builder
	b.WriteString("// Code generated by gen_asn_ranges.go from IANA as-numbers-2.csv; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("type asnRange struct{ start, end uint32 }\n\n")
	b.WriteString("var allocatedASNRanges = []asnRange{\n")
	for _, r := range ranges {
		fmt.Fprintf(&b, "\t{%d, %d},\n", r.start, r.end)
	}
	b.WriteString("}\n")
	return os.WriteFile(outputFile, []byte(b.String()), 0o644)
}
