// Code generated by gen_asn_ranges.go; DO NOT EDIT.
//
// Source: the IANA AS number registries as-numbers-1.csv (16-bit) and
// as-numbers-2.csv (32-bit), keeping only ranges delegated to an RIR.
// Touching ranges are merged when they share a registry, so entries do
// not map 1:1 to registry rows.

package asnreg

var registries = []Registry{
	{Name: "AFRINIC", WHOISHost: "whois.afrinic.net", RDAPBase: "https://rdap.afrinic.net/rdap/"},
	{Name: "APNIC", WHOISHost: "whois.apnic.net", RDAPBase: "https://rdap.apnic.net/"},
	{Name: "ARIN", WHOISHost: "whois.arin.net", RDAPBase: "https://rdap.arin.net/registry"},
	{Name: "LACNIC", WHOISHost: "whois.lacnic.net", RDAPBase: "https://rdap.lacnic.net/rdap/"},
	{Name: "RIPE NCC", WHOISHost: "whois.ripe.net", RDAPBase: "https://rdap.db.ripe.net/"},
}

// ranges is sorted by start and non-overlapping, which Lookup relies on
// for its binary search.
var ranges = []asnRange{
	{1, 1876, 2}, // ARIN
	{1877, 1901, 4}, // RIPE NCC
	{1902, 2042, 2}, // ARIN
	{2043, 2043, 4}, // RIPE NCC
	{2044, 2046, 2}, // ARIN
	{2047, 2047, 4}, // RIPE NCC
	{2048, 2106, 2}, // ARIN
	{2107, 2136, 4}, // RIPE NCC
	{2137, 2584, 2}, // ARIN
	{2585, 2614, 4}, // RIPE NCC
	{2615, 2772, 2}, // ARIN
	{2773, 2822, 4}, // RIPE NCC
	{2823, 2829, 2}, // ARIN
	{2830, 2879, 4}, // RIPE NCC
	{2880, 3153, 2}, // ARIN
	{3154, 3353, 4}, // RIPE NCC
	{3354, 4607, 2}, // ARIN
	{4608, 4865, 1}, // APNIC
	{4866, 5376, 2}, // ARIN
	{5377, 5631, 4}, // RIPE NCC
	{5632, 6655, 2}, // ARIN
	{6656, 6911, 4}, // RIPE NCC
	{6912, 7466, 2}, // ARIN
	{7467, 7722, 1}, // APNIC
	{7723, 8191, 2}, // ARIN
	{8192, 9215, 4}, // RIPE NCC
	{9216, 10239, 1}, // APNIC
	{10240, 12287, 2}, // ARIN
	{12288, 13311, 4}, // RIPE NCC
	{13312, 15359, 2}, // ARIN
	{15360, 16383, 4}, // RIPE NCC
	{16384, 17407, 2}, // ARIN
	{17408, 18431, 1}, // APNIC
	{18432, 20479, 2}, // ARIN
	{20480, 21503, 4}, // RIPE NCC
	{21504, 23455, 2}, // ARIN
	{23457, 23551, 2}, // ARIN
	{23552, 24575, 1}, // APNIC
	{24576, 25599, 4}, // RIPE NCC
	{25600, 27647, 2}, // ARIN
	{27648, 28671, 3}, // LACNIC
	{28672, 29695, 4}, // RIPE NCC
	{29696, 30719, 2}, // ARIN
	{30720, 31743, 4}, // RIPE NCC
	{31744, 33791, 2}, // ARIN
	{33792, 35839, 4}, // RIPE NCC
	{35840, 36863, 2}, // ARIN
	{36864, 37887, 0}, // AFRINIC
	{37888, 38911, 1}, // APNIC
	{38912, 39935, 4}, // RIPE NCC
	{39936, 40959, 2}, // ARIN
	{40960, 45055, 4}, // RIPE NCC
	{45056, 46079, 1}, // APNIC
	{46080, 47103, 2}, // ARIN
	{47104, 52223, 4}, // RIPE NCC
	{52224, 53247, 3}, // LACNIC
	{53248, 55295, 2}, // ARIN
	{55296, 56319, 1}, // APNIC
	{56320, 58367, 4}, // RIPE NCC
	{58368, 59391, 1}, // APNIC
	{59392, 61439, 4}, // RIPE NCC
	{61440, 61951, 3}, // LACNIC
	{61952, 62463, 4}, // RIPE NCC
	{62464, 63487, 2}, // ARIN
	{63488, 64098, 1}, // APNIC
	{64099, 64197, 3}, // LACNIC
	{64198, 64296, 2}, // ARIN
	{64297, 64395, 1}, // APNIC
	{64396, 64495, 4}, // RIPE NCC
	{131072, 155961, 1}, // APNIC
	{196608, 219547, 4}, // RIPE NCC
	{262144, 275868, 3}, // LACNIC
	{327680, 330751, 0}, // AFRINIC
	{393216, 404380, 2}, // ARIN
}
